version: '3'

services:
  node0:
    container_name: node0
    image: "tendermint/localnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    command: node --proxy_app=tcp://abci0:26658
    depends_on:
      - abci0
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  abci0:
    container_name: abci0
    image: "tendermint/dkg-node"
    command: ./dkg-node --socket-addr tcp://abci0:26658
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  node1:
    container_name: node1
    image: "tendermint/localnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    command: node --proxy_app=tcp://abci1:26658
    depends_on:
      - abci1
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  abci1:
    container_name: abci1
    image: "tendermint/dkg-node"
    command: ./dkg-node --socket-addr tcp://abci1:26658
    networks:
      localnet:
        ipv4_address: 192.167.10.7

  node2:
    container_name: node2
    image: "tendermint/localnode"
    environment:
      - ID=2
      - LOG=${LOG:-tendermint.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    command: node --proxy_app=tcp://abci2:26658
    depends_on:
      - abci2
    networks:
      localnet:
        ipv4_address: 192.167.10.4
  
  abci2:
    container_name: abci2
    image: "tendermint/dkg-node"
    command: ./dkg-node --socket-addr tcp://abci2:26658
    networks:
      localnet:
        ipv4_address: 192.167.10.8

  node3:
    container_name: node3
    image: "tendermint/localnode"
    environment:
      - ID=3
      - LOG=${LOG:-tendermint.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    command: node --proxy_app=tcp://abci3:26658
    depends_on:
      - abci3
    networks:
      localnet:
        ipv4_address: 192.167.10.5

  abci3:
    container_name: abci3
    image: "tendermint/dkg-node"
    command: ./dkg-node --socket-addr tcp://abci3:26658
    networks:
      localnet:
        ipv4_address: 192.167.10.9
        

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16